name: Pipette
description: A project for the Devathon contest... for now.
version: 1.0.0
author: Scarsz

main: org.devathon.contest2016.DevathonPlugin

permissions:
  pipette.build:
    description: Gives access to building all kinds of pipettes
    default: op
  pipette.build.item:
    description: Gives access to building item pipettes
    default: op
  pipette.build.liquid:
    description: Gives access to building liquid pipettes
    default: op